export interface Snippet {
  label: string;
  expression: string;
}

export const EXPRESSION_SNIPPETS: Snippet[] = [
  // String
  { label: "concat", expression: "concat('Hello', ' ', 'World')" },
  { label: "toLower", expression: "toLower('Hello World')" },
  { label: "toUpper", expression: "toUpper('hello')" },
  { label: "length", expression: "length('hello')" },
  { label: "substring", expression: "substring('hello', 1, 3)" },
  { label: "split", expression: "split('a,b,c', ',')" },
  { label: "replace", expression: "replace('hello world', 'world', 'there')" },
  { label: "trim", expression: "trim('  hello  ')" },
  { label: "startsWith", expression: "startsWith('hello', 'he')" },
  { label: "endsWith", expression: "endsWith('hello', 'lo')" },
  { label: "formatNumber", expression: "formatNumber(17.35, 'C2')" },
  { label: "isFloat", expression: "isFloat('10,000.00')" },
  { label: "isInt", expression: "isInt('123')" },
  { label: "lastIndexOf", expression: "lastIndexOf('hello world hello world', 'world')" },
  { label: "nthIndexOf", expression: "nthIndexOf('123456789123465789', '1', 2)" },
  // Math
  { label: "add", expression: "add(1, 2)" },
  { label: "sub", expression: "sub(10, 3)" },
  { label: "mul", expression: "mul(4, 5)" },
  { label: "div", expression: "div(10, 2)" },
  { label: "mod", expression: "mod(10, 3)" },
  { label: "min", expression: "min(1, 5, 3)" },
  { label: "max", expression: "max(1, 5, 3)" },
  { label: "range", expression: "range(1, 4)" },
  { label: "rand", expression: "rand(1, 5)" },
  // Logical
  { label: "and", expression: "and(equals(1, 1), equals(2, 2))" },
  { label: "or", expression: "or(equals(1, 2), equals(2, 2))" },
  { label: "not", expression: "not(equals(1, 2))" },
  { label: "equals", expression: "equals('hello', 'hello')" },
  { label: "if", expression: "if(equals(1, 1), 'yes', 'no')" },
  { label: "greater", expression: "greater(10, 5)" },
  { label: "less", expression: "less(5, 10)" },
  { label: "greaterOrEquals", expression: "greaterOrEquals(5, 5)" },
  { label: "lessOrEquals", expression: "lessOrEquals(5, 10)" },
  { label: "coalesce", expression: "coalesce(null, 'fallback')" },
  // Manipulation
  { label: "addProperty", expression: "addProperty(json('{\"firstName\": \"Sophia\", \"lastName\": \"Owen\"}'), 'middleName', 'Anne')" },
  { label: "removeProperty", expression: "removeProperty(json('{\"a\": 1, \"b\": 2}'), 'b')" },
  { label: "setProperty", expression: "setProperty(json('{\"firstName\": \"Sophia\", \"surName\": \"Owen\"}'), 'surName', 'Hartnett')" },
  // Conversion
  { label: "int", expression: "int('123')" },
  { label: "float", expression: "float('3.14')" },
  { label: "string", expression: "string(42)" },
  { label: "bool", expression: "bool('true')" },
  { label: "json", expression: "json('{\"a\": 1}')" },
  { label: "array", expression: "array('hello')" },
  { label: "createArray", expression: "createArray('a', 'b', 'c')" },
  { label: "base64", expression: "base64('hello')" },
  { label: "base64ToString", expression: "base64ToString('aGVsbG8=')" },
  { label: "base64ToBinary", expression: "base64ToBinary('aGVsbG8=')" },
  { label: "binary", expression: "binary('hello')" },
  { label: "decodeUriComponent", expression: "decodeUriComponent('https%3A%2F%2Fcontoso.com')" },
  { label: "encodeUriComponent", expression: "encodeUriComponent('https://contoso.com')" },
  { label: "uriComponent", expression: "uriComponent('https://contoso.com')" },
  { label: "uriComponentToString", expression: "uriComponentToString('https%3A%2F%2Fcontoso.com')" },
  { label: "uriComponentToBinary", expression: "uriComponentToBinary('https%3A%2F%2Fcontoso.com')" },
  { label: "dataUri", expression: "dataUri('hello')" },
  { label: "dataUriToString", expression: "dataUriToString('data:text/plain;charset=utf-8;base64,aGVsbG8=')" },
  { label: "dataUriToBinary", expression: "dataUriToBinary('data:text/plain;charset=utf-8;base64,aGVsbG8=')" },
  { label: "decodeDataUri", expression: "decodeDataUri('data:text/plain;charset=utf-8;base64,aGVsbG8=')" },
  { label: "decimal", expression: "decimal('1.2345678912312131')" },
  { label: "uriHost", expression: "uriHost('https://www.localhost.com:8080')" },
  { label: "uriPath", expression: "uriPath('https://www.contoso.com/catalog/shownew.htm?date=today')" },
  { label: "uriPathAndQuery", expression: "uriPathAndQuery('https://www.contoso.com/catalog/shownew.htm?date=today')" },
  { label: "uriPort", expression: "uriPort('https://www.localhost.com:8080')" },
  { label: "uriQuery", expression: "uriQuery('https://www.contoso.com/catalog/shownew.htm?date=today')" },
  { label: "uriScheme", expression: "uriScheme('https://www.contoso.com')" },
  // Collection
  { label: "first", expression: "first('hello')" },
  { label: "last", expression: "last('hello')" },
  { label: "join", expression: "join(createArray('a', 'b', 'c'), ', ')" },
  { label: "take", expression: "take('hello', 2)" },
  { label: "skip", expression: "skip('hello', 2)" },
  { label: "contains", expression: "contains('hello', 'ell')" },
  { label: "empty", expression: "empty('')" },
  { label: "union", expression: "union(createArray(1, 2), createArray(2, 3))" },
  { label: "intersection", expression: "intersection(createArray(1, 2), createArray(2, 3))" },
  { label: "chunk", expression: "chunk('abcdefghijklmnopqrstuvwxyz', 10)" },
  { label: "reverse", expression: "reverse('hello')" },
  { label: "sort", expression: "sort(createArray(2, 1, 0, 3))" },
  // DateTime
  { label: "utcNow", expression: "utcNow('yyyy-MM-dd')" },
  { label: "addDays", expression: "addDays('2025-02-16', 7, 'yyyy-MM-dd')" },
  { label: "addHours", expression: "addHours('2025-02-16T10:00:00', 2, 'yyyy-MM-ddTHH:mm:ss')" },
  { label: "formatDateTime", expression: "formatDateTime(utcNow(), 'yyyy-MM-dd')" },
  { label: "startOfDay", expression: "startOfDay('2025-02-16T14:30:45', 'yyyy-MM-ddTHH:mm:ss')" },
  { label: "addMinutes", expression: "addMinutes('2018-03-15T00:10:00Z', 10)" },
  { label: "addSeconds", expression: "addSeconds('2018-03-15T00:00:00Z', 10)" },
  { label: "addToTime", expression: "addToTime('2018-01-01T00:00:00Z', 1, 'Day')" },
  { label: "subtractFromTime", expression: "subtractFromTime('2018-01-02T00:00:00Z', 1, 'Day')" },
  { label: "getFutureTime", expression: "getFutureTime(5, 'Day')" },
  { label: "getPastTime", expression: "getPastTime(5, 'Day')" },
  { label: "dateDifference", expression: "dateDifference('2015-02-08', '2018-07-30')" },
  { label: "dayOfMonth", expression: "dayOfMonth('2018-03-15T13:27:36Z')" },
  { label: "dayOfWeek", expression: "dayOfWeek('2018-03-15T13:27:36Z')" },
  { label: "dayOfYear", expression: "dayOfYear('2018-03-15T13:27:36Z')" },
  { label: "startOfHour", expression: "startOfHour('2018-03-15T13:30:30Z')" },
  { label: "startOfMonth", expression: "startOfMonth('2018-03-15T13:30:30Z')" },
  { label: "parseDateTime", expression: "parseDateTime('20/10/2014', 'fr-fr')" },
  { label: "ticks", expression: "ticks('2018-01-01T00:00:00Z')" },
  { label: "convertFromUtc", expression: "convertFromUtc('2018-01-01T00:00:00Z', 'America/Los_Angeles')" },
  { label: "convertTimeZone", expression: "convertTimeZone('2018-01-01T00:00:00Z', 'UTC', 'America/Los_Angeles')" },
  { label: "convertToUtc", expression: "convertToUtc('2018-01-01T00:00:00', 'America/Los_Angeles')" },
  // Workflow
  { label: "parameters", expression: "parameters('firstName')" },
  { label: "variables", expression: "variables('myVar')" },
  { label: "triggerBody", expression: "triggerBody()" },
];

/** Snippets sorted alphabetically by label (for UI display). */
export const EXPRESSION_SNIPPETS_SORTED: Snippet[] = [...EXPRESSION_SNIPPETS].sort(
  (a, b) => a.label.localeCompare(b.label, undefined, { sensitivity: "base" }),
);
